// Datos compartidos - generado automaticamente
var SEED_RESULTS = [
  {id:1,type:'numeric',exam:'Creatinina',value:0.87,unit:'mg/dL',date:'2023-07-15',cat:'Rinon',lab:'BioNet La Florida',notes:''},
  {id:2,type:'numeric',exam:'Vitamina B12',value:239,unit:'pg/mL',date:'2023-07-15',cat:'Vitaminas',lab:'BioNet La Florida',notes:''},
  {id:3,type:'numeric',exam:'Colesterol total',value:171,unit:'mg/dL',date:'2023-07-15',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:4,type:'numeric',exam:'Colesterol HDL',value:48.7,unit:'mg/dL',date:'2023-07-15',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:5,type:'numeric',exam:'Colesterol LDL',value:109.9,unit:'mg/dL',date:'2023-07-15',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:6,type:'numeric',exam:'Trigliceridos',value:62,unit:'mg/dL',date:'2023-07-15',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:7,type:'numeric',exam:'Glucosa',value:88,unit:'mg/dL',date:'2023-07-15',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:8,type:'numeric',exam:'Acido urico',value:3.1,unit:'mg/dL',date:'2023-07-15',cat:'Rinon',lab:'BioNet La Florida',notes:'Bajo rango'},
  {id:9,type:'numeric',exam:'Proteinas totales',value:7.3,unit:'gr/dL',date:'2023-07-15',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:10,type:'numeric',exam:'Albumina',value:4.2,unit:'gr/dL',date:'2023-07-15',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:11,type:'numeric',exam:'Calcio',value:8.8,unit:'mg/dL',date:'2023-07-15',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:12,type:'numeric',exam:'Fosforo',value:3.8,unit:'mg/dL',date:'2023-07-15',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:13,type:'numeric',exam:'Bilirrubina total',value:0.6,unit:'mg/dL',date:'2023-07-15',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:14,type:'numeric',exam:'Fosfatasa alcalina',value:59,unit:'U/L',date:'2023-07-15',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:15,type:'numeric',exam:'LDH',value:139,unit:'U/L',date:'2023-07-15',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:16,type:'numeric',exam:'SGOT-GOT',value:14,unit:'U/L',date:'2023-07-15',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:17,type:'numeric',exam:'SGPT-GPT',value:17,unit:'U/L',date:'2023-07-15',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:18,type:'numeric',exam:'GGT',value:13,unit:'U/L',date:'2023-07-15',cat:'Higado',lab:'BioNet La Florida',notes:'Bajo rango'},
  {id:19,type:'numeric',exam:'Vitamina D',value:18,unit:'ng/mL',date:'2023-07-15',cat:'Vitaminas',lab:'BioNet La Florida',notes:'Bajo rango'},
  {id:20,type:'numeric',exam:'Hemoglobina',value:16.4,unit:'gr/dL',date:'2023-07-15',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:21,type:'numeric',exam:'Hematocrito',value:48.5,unit:'%',date:'2023-07-15',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:22,type:'numeric',exam:'Leucocitos',value:4.2,unit:'k/uL',date:'2023-07-15',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:23,type:'numeric',exam:'Plaquetas',value:202,unit:'k/uL',date:'2023-07-15',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:24,type:'numeric',exam:'TSH',value:1.34,unit:'mUI/L',date:'2023-07-15',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:25,type:'numeric',exam:'T4 libre',value:1.16,unit:'ng/dL',date:'2023-07-15',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:26,type:'numeric',exam:'Insulina basal',value:4.4,unit:'uUI/mL',date:'2023-07-15',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:27,type:'numeric',exam:'HOMA IR',value:1,unit:'indice',date:'2023-07-15',cat:'Sangre',lab:'BioNet La Florida',notes:'Ref menos de 2.5'},
  {id:28,type:'qualitative',exam:'VDRL',qualResult:'No Reactivo',date:'2023-07-15',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:29,type:'qualitative',exam:'VIH Anticuerpos',qualResult:'No Reactivo',date:'2023-07-15',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:30,type:'qualitative',exam:'Hepatitis B HBsAg',qualResult:'No Reactivo',date:'2023-07-15',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:31,type:'numeric',exam:'Vitamina B12',value:263,unit:'pg/mL',date:'2025-01-30',cat:'Vitaminas',lab:'BioNet La Florida',notes:''},
  {id:32,type:'numeric',exam:'Creatinina',value:0.96,unit:'mg/dL',date:'2025-01-30',cat:'Rinon',lab:'BioNet La Florida',notes:''},
  {id:33,type:'numeric',exam:'Sodio',value:141,unit:'mEq/L',date:'2025-01-30',cat:'Electrolitos',lab:'BioNet La Florida',notes:''},
  {id:34,type:'numeric',exam:'Potasio',value:3.9,unit:'mEq/L',date:'2025-01-30',cat:'Electrolitos',lab:'BioNet La Florida',notes:''},
  {id:35,type:'numeric',exam:'Cloro',value:106,unit:'mEq/L',date:'2025-01-30',cat:'Electrolitos',lab:'BioNet La Florida',notes:''},
  {id:36,type:'numeric',exam:'Colesterol total',value:164,unit:'mg/dL',date:'2025-01-30',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:37,type:'numeric',exam:'Colesterol HDL',value:51.6,unit:'mg/dL',date:'2025-01-30',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:38,type:'numeric',exam:'Colesterol LDL',value:96.4,unit:'mg/dL',date:'2025-01-30',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:39,type:'numeric',exam:'Trigliceridos',value:80,unit:'mg/dL',date:'2025-01-30',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:40,type:'numeric',exam:'Glucosa',value:83,unit:'mg/dL',date:'2025-01-30',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:41,type:'numeric',exam:'Acido urico',value:4.2,unit:'mg/dL',date:'2025-01-30',cat:'Rinon',lab:'BioNet La Florida',notes:''},
  {id:42,type:'numeric',exam:'Proteinas totales',value:7.1,unit:'gr/dL',date:'2025-01-30',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:43,type:'numeric',exam:'Albumina',value:4,unit:'gr/dL',date:'2025-01-30',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:44,type:'numeric',exam:'Calcio',value:8.9,unit:'mg/dL',date:'2025-01-30',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:45,type:'numeric',exam:'Fosforo',value:3.2,unit:'mg/dL',date:'2025-01-30',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:46,type:'numeric',exam:'Bilirrubina total',value:1,unit:'mg/dL',date:'2025-01-30',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:47,type:'numeric',exam:'Fosfatasa alcalina',value:55,unit:'U/L',date:'2025-01-30',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:48,type:'numeric',exam:'LDH',value:158,unit:'U/L',date:'2025-01-30',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:49,type:'numeric',exam:'SGOT-GOT',value:16,unit:'U/L',date:'2025-01-30',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:50,type:'numeric',exam:'SGPT-GPT',value:21,unit:'U/L',date:'2025-01-30',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:51,type:'numeric',exam:'GGT',value:17,unit:'U/L',date:'2025-01-30',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:52,type:'numeric',exam:'Vitamina D',value:26.9,unit:'ng/mL',date:'2025-01-30',cat:'Vitaminas',lab:'BioNet La Florida',notes:''},
  {id:53,type:'numeric',exam:'Hemoglobina',value:15.5,unit:'gr/dL',date:'2025-01-30',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:54,type:'numeric',exam:'Hematocrito',value:45.1,unit:'%',date:'2025-01-30',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:55,type:'numeric',exam:'Leucocitos',value:4.6,unit:'k/uL',date:'2025-01-30',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:56,type:'numeric',exam:'Plaquetas',value:188,unit:'k/uL',date:'2025-01-30',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:57,type:'numeric',exam:'TSH',value:2.96,unit:'mUI/L',date:'2025-01-30',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:58,type:'numeric',exam:'T4 libre',value:1.51,unit:'ng/dL',date:'2025-01-30',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:59,type:'numeric',exam:'T4 total',value:7.8,unit:'ug/dL',date:'2025-01-30',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:60,type:'numeric',exam:'T3 total',value:1.24,unit:'ng/mL',date:'2025-01-30',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:61,type:'numeric',exam:'Insulina basal',value:4.4,unit:'uUI/mL',date:'2025-01-30',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:62,type:'numeric',exam:'HOMA IR',value:0.9,unit:'indice',date:'2025-01-30',cat:'Sangre',lab:'BioNet La Florida',notes:'Ref menos de 2.5'},
  {id:63,type:'qualitative',exam:'VDRL',qualResult:'No Reactivo',date:'2025-01-30',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:64,type:'qualitative',exam:'VIH Anticuerpos',qualResult:'No Reactivo',date:'2025-01-30',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:65,type:'qualitative',exam:'Hepatitis B HBsAg',qualResult:'No Reactivo',date:'2025-01-30',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:66,type:'qualitative',exam:'Hepatitis C Anti-HVC',qualResult:'No Reactivo',date:'2025-01-30',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:67,type:'qualitative',exam:'Hepatitis A IgM',qualResult:'No Reactivo',date:'2025-01-30',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:68,type:'qualitative',exam:'Hepatitis A IgG',qualResult:'No Reactivo',date:'2025-01-30',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:69,type:'qualitative',exam:'Herpes II IgG',qualResult:'No Reactivo',date:'2025-01-30',cat:'Serologia',lab:'BioNet La Florida',notes:'Valor 0.22'},
  {id:70,type:'qualitative',exam:'Herpes I IgM',qualResult:'No Reactivo',date:'2025-01-30',cat:'Serologia',lab:'BioNet La Florida',notes:'Valor 0.34'},
  {id:71,type:'qualitative',exam:'Panel ITS PCR',qualResult:'Negativo',date:'2025-01-30',cat:'Serologia',lab:'BioNet La Florida',notes:'7 patogenos negativos'},
  {id:72,type:'numeric',exam:'Vitamina B12',value:301,unit:'pg/mL',date:'2025-09-02',cat:'Vitaminas',lab:'BioNet La Florida',notes:''},
  {id:73,type:'numeric',exam:'Creatinina',value:1.0,unit:'mg/dL',date:'2025-09-02',cat:'Rinon',lab:'BioNet La Florida',notes:''},
  {id:74,type:'numeric',exam:'Glucosa',value:82,unit:'mg/dL',date:'2025-09-02',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:75,type:'numeric',exam:'Sodio',value:142,unit:'mEq/L',date:'2025-09-02',cat:'Electrolitos',lab:'BioNet La Florida',notes:''},
  {id:76,type:'numeric',exam:'Potasio',value:4.6,unit:'mEq/L',date:'2025-09-02',cat:'Electrolitos',lab:'BioNet La Florida',notes:''},
  {id:77,type:'numeric',exam:'Cloro',value:105,unit:'mEq/L',date:'2025-09-02',cat:'Electrolitos',lab:'BioNet La Florida',notes:''},
  {id:78,type:'numeric',exam:'Colesterol total',value:215,unit:'mg/dL',date:'2025-09-02',cat:'Sangre',lab:'BioNet La Florida',notes:'Elevado'},
  {id:79,type:'numeric',exam:'Colesterol HDL',value:54,unit:'mg/dL',date:'2025-09-02',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:80,type:'numeric',exam:'Colesterol LDL',value:146.2,unit:'mg/dL',date:'2025-09-02',cat:'Sangre',lab:'BioNet La Florida',notes:'Limite alto'},
  {id:81,type:'numeric',exam:'Trigliceridos',value:74,unit:'mg/dL',date:'2025-09-02',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:82,type:'numeric',exam:'Acido urico',value:3.8,unit:'mg/dL',date:'2025-09-02',cat:'Rinon',lab:'BioNet La Florida',notes:''},
  {id:83,type:'numeric',exam:'Proteinas totales',value:7.4,unit:'gr/dL',date:'2025-09-02',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:84,type:'numeric',exam:'Albumina',value:4,unit:'gr/dL',date:'2025-09-02',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:85,type:'numeric',exam:'Calcio',value:9.7,unit:'mg/dL',date:'2025-09-02',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:86,type:'numeric',exam:'Fosforo',value:4.1,unit:'mg/dL',date:'2025-09-02',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:87,type:'numeric',exam:'Bilirrubina total',value:0.59,unit:'mg/dL',date:'2025-09-02',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:88,type:'numeric',exam:'Fosfatasa alcalina',value:52,unit:'U/L',date:'2025-09-02',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:89,type:'numeric',exam:'LDH',value:170,unit:'U/L',date:'2025-09-02',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:90,type:'numeric',exam:'SGOT-GOT',value:19,unit:'U/L',date:'2025-09-02',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:91,type:'numeric',exam:'SGPT-GPT',value:18,unit:'U/L',date:'2025-09-02',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:92,type:'numeric',exam:'GGT',value:17,unit:'U/L',date:'2025-09-02',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:93,type:'numeric',exam:'Vitamina D',value:23.3,unit:'ng/mL',date:'2025-09-02',cat:'Vitaminas',lab:'BioNet La Florida',notes:''},
  {id:94,type:'numeric',exam:'Hemoglobina',value:15.8,unit:'gr/dL',date:'2025-09-02',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:95,type:'numeric',exam:'Hematocrito',value:45.5,unit:'%',date:'2025-09-02',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:96,type:'numeric',exam:'Leucocitos',value:5.5,unit:'k/uL',date:'2025-09-02',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:97,type:'numeric',exam:'Plaquetas',value:239,unit:'k/uL',date:'2025-09-02',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:98,type:'numeric',exam:'TSH',value:3.02,unit:'mUI/L',date:'2025-09-02',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:99,type:'numeric',exam:'T4 libre',value:1.5,unit:'ng/dL',date:'2025-09-02',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:100,type:'numeric',exam:'T4 total',value:7.3,unit:'ug/dL',date:'2025-09-02',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:101,type:'numeric',exam:'T3 total',value:1.21,unit:'ng/mL',date:'2025-09-02',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:102,type:'numeric',exam:'Insulina basal',value:7.5,unit:'uUI/mL',date:'2025-09-02',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:103,type:'numeric',exam:'HOMA IR',value:1.5,unit:'indice',date:'2025-09-02',cat:'Sangre',lab:'BioNet La Florida',notes:'Ref menos de 2.5'},
  {id:104,type:'qualitative',exam:'VDRL',qualResult:'No Reactivo',date:'2025-09-02',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:105,type:'qualitative',exam:'VIH Anticuerpos',qualResult:'No Reactivo',date:'2025-09-02',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:106,type:'qualitative',exam:'Hepatitis B HBsAg',qualResult:'No Reactivo',date:'2025-09-02',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:107,type:'qualitative',exam:'Hepatitis C Anti-HVC',qualResult:'No Reactivo',date:'2025-09-02',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:108,type:'qualitative',exam:'Herpes II IgG',qualResult:'No Reactivo',date:'2025-09-02',cat:'Serologia',lab:'BioNet La Florida',notes:'Valor 0.13'},
  {id:109,type:'qualitative',exam:'Herpes I IgM',qualResult:'No Reactivo',date:'2025-09-02',cat:'Serologia',lab:'BioNet La Florida',notes:'Valor 0.33'}
];
var APP_SK = "miSalud_v5";
