// Datos compartidos - generado automaticamente
var SEED_RESULTS = [
  {id:1,type:'numeric',exam:'Creatinina',value:0.87,unit:'mg/dL',date:'2023-07-15',cat:'Rinon',lab:'BioNet La Florida',notes:''},
  {id:2,type:'numeric',exam:'Vitamina B12',value:239,unit:'pg/mL',date:'2023-07-15',cat:'Vitaminas',lab:'BioNet La Florida',notes:''},
  {id:3,type:'numeric',exam:'Colesterol total',value:171,unit:'mg/dL',date:'2023-07-15',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:4,type:'numeric',exam:'Colesterol HDL',value:48.7,unit:'mg/dL',date:'2023-07-15',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:5,type:'numeric',exam:'Colesterol LDL',value:109.9,unit:'mg/dL',date:'2023-07-15',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:6,type:'numeric',exam:'Trigliceridos',value:62,unit:'mg/dL',date:'2023-07-15',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:7,type:'numeric',exam:'Glucosa',value:88,unit:'mg/dL',date:'2023-07-15',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:8,type:'numeric',exam:'Acido urico',value:3.1,unit:'mg/dL',date:'2023-07-15',cat:'Rinon',lab:'BioNet La Florida',notes:'Bajo rango'},
  {id:9,type:'numeric',exam:'Proteinas totales',value:7.3,unit:'gr/dL',date:'2023-07-15',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:10,type:'numeric',exam:'Albumina',value:4.2,unit:'gr/dL',date:'2023-07-15',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:11,type:'numeric',exam:'Calcio',value:8.8,unit:'mg/dL',date:'2023-07-15',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:12,type:'numeric',exam:'Fosforo',value:3.8,unit:'mg/dL',date:'2023-07-15',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:13,type:'numeric',exam:'Bilirrubina total',value:0.6,unit:'mg/dL',date:'2023-07-15',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:14,type:'numeric',exam:'Fosfatasa alcalina',value:59,unit:'U/L',date:'2023-07-15',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:15,type:'numeric',exam:'LDH',value:139,unit:'U/L',date:'2023-07-15',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:16,type:'numeric',exam:'SGOT-GOT',value:14,unit:'U/L',date:'2023-07-15',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:17,type:'numeric',exam:'SGPT-GPT',value:17,unit:'U/L',date:'2023-07-15',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:18,type:'numeric',exam:'GGT',value:13,unit:'U/L',date:'2023-07-15',cat:'Higado',lab:'BioNet La Florida',notes:'Bajo rango'},
  {id:19,type:'numeric',exam:'Vitamina D',value:18,unit:'ng/mL',date:'2023-07-15',cat:'Vitaminas',lab:'BioNet La Florida',notes:'Bajo rango'},
  {id:20,type:'numeric',exam:'Hemoglobina',value:16.4,unit:'gr/dL',date:'2023-07-15',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:21,type:'numeric',exam:'Hematocrito',value:48.5,unit:'%',date:'2023-07-15',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:22,type:'numeric',exam:'Leucocitos',value:4.2,unit:'k/uL',date:'2023-07-15',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:23,type:'numeric',exam:'Plaquetas',value:202,unit:'k/uL',date:'2023-07-15',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:24,type:'numeric',exam:'TSH',value:1.34,unit:'mUI/L',date:'2023-07-15',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:25,type:'numeric',exam:'T4 libre',value:1.16,unit:'ng/dL',date:'2023-07-15',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:26,type:'numeric',exam:'Insulina basal',value:4.4,unit:'uUI/mL',date:'2023-07-15',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:27,type:'numeric',exam:'HOMA IR',value:1,unit:'indice',date:'2023-07-15',cat:'Sangre',lab:'BioNet La Florida',notes:'Ref menos de 2.5'},
  {id:28,type:'qualitative',exam:'VDRL',qualResult:'No Reactivo',date:'2023-07-15',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:29,type:'qualitative',exam:'VIH Anticuerpos',qualResult:'No Reactivo',date:'2023-07-15',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:30,type:'qualitative',exam:'Hepatitis B HBsAg',qualResult:'No Reactivo',date:'2023-07-15',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:31,type:'numeric',exam:'Vitamina B12',value:263,unit:'pg/mL',date:'2025-01-30',cat:'Vitaminas',lab:'BioNet La Florida',notes:''},
  {id:32,type:'numeric',exam:'Creatinina',value:0.96,unit:'mg/dL',date:'2025-01-30',cat:'Rinon',lab:'BioNet La Florida',notes:''},
  {id:33,type:'numeric',exam:'Sodio',value:141,unit:'mEq/L',date:'2025-01-30',cat:'Electrolitos',lab:'BioNet La Florida',notes:''},
  {id:34,type:'numeric',exam:'Potasio',value:3.9,unit:'mEq/L',date:'2025-01-30',cat:'Electrolitos',lab:'BioNet La Florida',notes:''},
  {id:35,type:'numeric',exam:'Cloro',value:106,unit:'mEq/L',date:'2025-01-30',cat:'Electrolitos',lab:'BioNet La Florida',notes:''},
  {id:36,type:'numeric',exam:'Colesterol total',value:164,unit:'mg/dL',date:'2025-01-30',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:37,type:'numeric',exam:'Colesterol HDL',value:51.6,unit:'mg/dL',date:'2025-01-30',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:38,type:'numeric',exam:'Colesterol LDL',value:96.4,unit:'mg/dL',date:'2025-01-30',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:39,type:'numeric',exam:'Trigliceridos',value:80,unit:'mg/dL',date:'2025-01-30',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:40,type:'numeric',exam:'Glucosa',value:83,unit:'mg/dL',date:'2025-01-30',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:41,type:'numeric',exam:'Acido urico',value:4.2,unit:'mg/dL',date:'2025-01-30',cat:'Rinon',lab:'BioNet La Florida',notes:''},
  {id:42,type:'numeric',exam:'Proteinas totales',value:7.1,unit:'gr/dL',date:'2025-01-30',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:43,type:'numeric',exam:'Albumina',value:4,unit:'gr/dL',date:'2025-01-30',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:44,type:'numeric',exam:'Calcio',value:8.9,unit:'mg/dL',date:'2025-01-30',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:45,type:'numeric',exam:'Fosforo',value:3.2,unit:'mg/dL',date:'2025-01-30',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:46,type:'numeric',exam:'Bilirrubina total',value:1,unit:'mg/dL',date:'2025-01-30',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:47,type:'numeric',exam:'Fosfatasa alcalina',value:55,unit:'U/L',date:'2025-01-30',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:48,type:'numeric',exam:'LDH',value:158,unit:'U/L',date:'2025-01-30',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:49,type:'numeric',exam:'SGOT-GOT',value:16,unit:'U/L',date:'2025-01-30',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:50,type:'numeric',exam:'SGPT-GPT',value:21,unit:'U/L',date:'2025-01-30',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:51,type:'numeric',exam:'GGT',value:17,unit:'U/L',date:'2025-01-30',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:52,type:'numeric',exam:'Vitamina D',value:26.9,unit:'ng/mL',date:'2025-01-30',cat:'Vitaminas',lab:'BioNet La Florida',notes:''},
  {id:53,type:'numeric',exam:'Hemoglobina',value:15.5,unit:'gr/dL',date:'2025-01-30',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:54,type:'numeric',exam:'Hematocrito',value:45.1,unit:'%',date:'2025-01-30',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:55,type:'numeric',exam:'Leucocitos',value:4.6,unit:'k/uL',date:'2025-01-30',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:56,type:'numeric',exam:'Plaquetas',value:188,unit:'k/uL',date:'2025-01-30',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:57,type:'numeric',exam:'TSH',value:2.96,unit:'mUI/L',date:'2025-01-30',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:58,type:'numeric',exam:'T4 libre',value:1.51,unit:'ng/dL',date:'2025-01-30',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:59,type:'numeric',exam:'T4 total',value:7.8,unit:'ug/dL',date:'2025-01-30',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:60,type:'numeric',exam:'T3 total',value:1.24,unit:'ng/mL',date:'2025-01-30',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:61,type:'numeric',exam:'Insulina basal',value:4.4,unit:'uUI/mL',date:'2025-01-30',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:62,type:'numeric',exam:'HOMA IR',value:0.9,unit:'indice',date:'2025-01-30',cat:'Sangre',lab:'BioNet La Florida',notes:'Ref menos de 2.5'},
  {id:63,type:'qualitative',exam:'VDRL',qualResult:'No Reactivo',date:'2025-01-30',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:64,type:'qualitative',exam:'VIH Anticuerpos',qualResult:'No Reactivo',date:'2025-01-30',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:65,type:'qualitative',exam:'Hepatitis B HBsAg',qualResult:'No Reactivo',date:'2025-01-30',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:66,type:'qualitative',exam:'Hepatitis C Anti-HVC',qualResult:'No Reactivo',date:'2025-01-30',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:67,type:'qualitative',exam:'Hepatitis A IgM',qualResult:'No Reactivo',date:'2025-01-30',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:68,type:'qualitative',exam:'Hepatitis A IgG',qualResult:'No Reactivo',date:'2025-01-30',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:69,type:'qualitative',exam:'Herpes II IgG',qualResult:'No Reactivo',date:'2025-01-30',cat:'Serologia',lab:'BioNet La Florida',notes:'Valor 0.22'},
  {id:70,type:'qualitative',exam:'Herpes I IgM',qualResult:'No Reactivo',date:'2025-01-30',cat:'Serologia',lab:'BioNet La Florida',notes:'Valor 0.34'},
  {id:71,type:'qualitative',exam:'Panel ITS PCR',qualResult:'Negativo',date:'2025-01-30',cat:'Serologia',lab:'BioNet La Florida',notes:'7 patogenos negativos'},
  {id:72,type:'numeric',exam:'Vitamina B12',value:301,unit:'pg/mL',date:'2025-09-02',cat:'Vitaminas',lab:'BioNet La Florida',notes:''},
  {id:73,type:'numeric',exam:'Creatinina',value:1.0,unit:'mg/dL',date:'2025-09-02',cat:'Rinon',lab:'BioNet La Florida',notes:''},
  {id:74,type:'numeric',exam:'Glucosa',value:82,unit:'mg/dL',date:'2025-09-02',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:75,type:'numeric',exam:'Sodio',value:142,unit:'mEq/L',date:'2025-09-02',cat:'Electrolitos',lab:'BioNet La Florida',notes:''},
  {id:76,type:'numeric',exam:'Potasio',value:4.6,unit:'mEq/L',date:'2025-09-02',cat:'Electrolitos',lab:'BioNet La Florida',notes:''},
  {id:77,type:'numeric',exam:'Cloro',value:105,unit:'mEq/L',date:'2025-09-02',cat:'Electrolitos',lab:'BioNet La Florida',notes:''},
  {id:78,type:'numeric',exam:'Colesterol total',value:215,unit:'mg/dL',date:'2025-09-02',cat:'Sangre',lab:'BioNet La Florida',notes:'Elevado'},
  {id:79,type:'numeric',exam:'Colesterol HDL',value:54,unit:'mg/dL',date:'2025-09-02',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:80,type:'numeric',exam:'Colesterol LDL',value:146.2,unit:'mg/dL',date:'2025-09-02',cat:'Sangre',lab:'BioNet La Florida',notes:'Limite alto'},
  {id:81,type:'numeric',exam:'Trigliceridos',value:74,unit:'mg/dL',date:'2025-09-02',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:82,type:'numeric',exam:'Acido urico',value:3.8,unit:'mg/dL',date:'2025-09-02',cat:'Rinon',lab:'BioNet La Florida',notes:''},
  {id:83,type:'numeric',exam:'Proteinas totales',value:7.4,unit:'gr/dL',date:'2025-09-02',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:84,type:'numeric',exam:'Albumina',value:4,unit:'gr/dL',date:'2025-09-02',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:85,type:'numeric',exam:'Calcio',value:9.7,unit:'mg/dL',date:'2025-09-02',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:86,type:'numeric',exam:'Fosforo',value:4.1,unit:'mg/dL',date:'2025-09-02',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:87,type:'numeric',exam:'Bilirrubina total',value:0.59,unit:'mg/dL',date:'2025-09-02',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:88,type:'numeric',exam:'Fosfatasa alcalina',value:52,unit:'U/L',date:'2025-09-02',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:89,type:'numeric',exam:'LDH',value:170,unit:'U/L',date:'2025-09-02',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:90,type:'numeric',exam:'SGOT-GOT',value:19,unit:'U/L',date:'2025-09-02',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:91,type:'numeric',exam:'SGPT-GPT',value:18,unit:'U/L',date:'2025-09-02',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:92,type:'numeric',exam:'GGT',value:17,unit:'U/L',date:'2025-09-02',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:93,type:'numeric',exam:'Vitamina D',value:23.3,unit:'ng/mL',date:'2025-09-02',cat:'Vitaminas',lab:'BioNet La Florida',notes:''},
  {id:94,type:'numeric',exam:'Hemoglobina',value:15.8,unit:'gr/dL',date:'2025-09-02',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:95,type:'numeric',exam:'Hematocrito',value:45.5,unit:'%',date:'2025-09-02',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:96,type:'numeric',exam:'Leucocitos',value:5.5,unit:'k/uL',date:'2025-09-02',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:97,type:'numeric',exam:'Plaquetas',value:239,unit:'k/uL',date:'2025-09-02',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:98,type:'numeric',exam:'TSH',value:3.02,unit:'mUI/L',date:'2025-09-02',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:99,type:'numeric',exam:'T4 libre',value:1.5,unit:'ng/dL',date:'2025-09-02',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:100,type:'numeric',exam:'T4 total',value:7.3,unit:'ug/dL',date:'2025-09-02',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:101,type:'numeric',exam:'T3 total',value:1.21,unit:'ng/mL',date:'2025-09-02',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:102,type:'numeric',exam:'Insulina basal',value:7.5,unit:'uUI/mL',date:'2025-09-02',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:103,type:'numeric',exam:'HOMA IR',value:1.5,unit:'indice',date:'2025-09-02',cat:'Sangre',lab:'BioNet La Florida',notes:'Ref menos de 2.5'},
  {id:104,type:'qualitative',exam:'VDRL',qualResult:'No Reactivo',date:'2025-09-02',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:105,type:'qualitative',exam:'VIH Anticuerpos',qualResult:'No Reactivo',date:'2025-09-02',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:106,type:'qualitative',exam:'Hepatitis B HBsAg',qualResult:'No Reactivo',date:'2025-09-02',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:107,type:'qualitative',exam:'Hepatitis C Anti-HVC',qualResult:'No Reactivo',date:'2025-09-02',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:108,type:'qualitative',exam:'Herpes II IgG',qualResult:'No Reactivo',date:'2025-09-02',cat:'Serologia',lab:'BioNet La Florida',notes:'Valor 0.13'},
  {id:109,type:'qualitative',exam:'Herpes I IgM',qualResult:'No Reactivo',date:'2025-09-02',cat:'Serologia',lab:'BioNet La Florida',notes:'Valor 0.33'},
  // === 14/03/2026 - BioNet La Florida ===
  // Numericos
  {id:110,type:'numeric',exam:'Vitamina B12',value:254,unit:'pg/mL',date:'2026-03-14',cat:'Vitaminas',lab:'BioNet La Florida',notes:''},
  {id:111,type:'numeric',exam:'Creatinina',value:1.02,unit:'mg/dL',date:'2026-03-14',cat:'Rinon',lab:'BioNet La Florida',notes:''},
  {id:112,type:'numeric',exam:'Sodio',value:143,unit:'mEq/L',date:'2026-03-14',cat:'Electrolitos',lab:'BioNet La Florida',notes:''},
  {id:113,type:'numeric',exam:'Potasio',value:4.1,unit:'mEq/L',date:'2026-03-14',cat:'Electrolitos',lab:'BioNet La Florida',notes:''},
  {id:114,type:'numeric',exam:'Cloro',value:104,unit:'mEq/L',date:'2026-03-14',cat:'Electrolitos',lab:'BioNet La Florida',notes:''},
  {id:115,type:'numeric',exam:'Colesterol total',value:197,unit:'mg/dL',date:'2026-03-14',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:116,type:'numeric',exam:'Colesterol HDL',value:47.1,unit:'mg/dL',date:'2026-03-14',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:117,type:'numeric',exam:'Colesterol LDL',value:130.7,unit:'mg/dL',date:'2026-03-14',cat:'Sangre',lab:'BioNet La Florida',notes:'Limite alto 130-159'},
  {id:118,type:'numeric',exam:'Trigliceridos',value:96,unit:'mg/dL',date:'2026-03-14',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:119,type:'numeric',exam:'Glucosa',value:79,unit:'mg/dL',date:'2026-03-14',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:120,type:'numeric',exam:'Acido urico',value:3.9,unit:'mg/dL',date:'2026-03-14',cat:'Rinon',lab:'BioNet La Florida',notes:''},
  {id:121,type:'numeric',exam:'Proteinas totales',value:7.6,unit:'gr/dL',date:'2026-03-14',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:122,type:'numeric',exam:'Albumina',value:4.4,unit:'gr/dL',date:'2026-03-14',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:123,type:'numeric',exam:'Calcio',value:9.1,unit:'mg/dL',date:'2026-03-14',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:124,type:'numeric',exam:'Fosforo',value:3.8,unit:'mg/dL',date:'2026-03-14',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:125,type:'numeric',exam:'Bilirrubina total',value:0.7,unit:'mg/dL',date:'2026-03-14',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:126,type:'numeric',exam:'Fosfatasa alcalina',value:53,unit:'U/L',date:'2026-03-14',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:127,type:'numeric',exam:'LDH',value:164,unit:'U/L',date:'2026-03-14',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:128,type:'numeric',exam:'SGOT-GOT',value:13.0,unit:'U/L',date:'2026-03-14',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:129,type:'numeric',exam:'SGPT-GPT',value:22.0,unit:'U/L',date:'2026-03-14',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:130,type:'numeric',exam:'GGT',value:17,unit:'U/L',date:'2026-03-14',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:131,type:'numeric',exam:'Vitamina D',value:29.1,unit:'ng/mL',date:'2026-03-14',cat:'Vitaminas',lab:'BioNet La Florida',notes:''},
  {id:132,type:'numeric',exam:'Hemoglobina',value:15.7,unit:'gr/dL',date:'2026-03-14',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:133,type:'numeric',exam:'Hematocrito',value:45.4,unit:'%',date:'2026-03-14',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:134,type:'numeric',exam:'VCM',value:100.3,unit:'fL',date:'2026-03-14',cat:'Sangre',lab:'BioNet La Florida',notes:'Macrocitosis leve - fuera de rango (82-99)'},
  {id:135,type:'numeric',exam:'HCM',value:34.8,unit:'pg',date:'2026-03-14',cat:'Sangre',lab:'BioNet La Florida',notes:'Fuera de rango (28-32)'},
  {id:136,type:'numeric',exam:'Plaquetas',value:217,unit:'k/uL',date:'2026-03-14',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:137,type:'numeric',exam:'Leucocitos',value:3.7,unit:'k/uL',date:'2026-03-14',cat:'Sangre',lab:'BioNet La Florida',notes:'Leucopenia leve - bajo rango (4.1-9.5)'},
  {id:138,type:'numeric',exam:'TSH',value:1.24,unit:'mUI/L',date:'2026-03-14',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:139,type:'numeric',exam:'T4 libre',value:1.56,unit:'ng/dL',date:'2026-03-14',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:140,type:'numeric',exam:'T4 total',value:6.3,unit:'ug/dL',date:'2026-03-14',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:141,type:'numeric',exam:'T3 total',value:1.33,unit:'ng/mL',date:'2026-03-14',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:142,type:'numeric',exam:'HOMA IR',value:1.1,unit:'indice',date:'2026-03-14',cat:'Sangre',lab:'BioNet La Florida',notes:'Ref menos de 2.5'},
  {id:143,type:'numeric',exam:'Insulina basal',value:5.6,unit:'uUI/mL',date:'2026-03-14',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:144,type:'numeric',exam:'IgE Dermatoph. pteronyssinus',value:2.7,unit:'IU/mL',date:'2026-03-14',cat:'Alergias',lab:'BioNet La Florida',notes:'Clase II - Positivo moderado (0.71-3.50)'},
  {id:145,type:'numeric',exam:'IgE Dermatofagoide farinae',value:3.4,unit:'IU/mL',date:'2026-03-14',cat:'Alergias',lab:'BioNet La Florida',notes:'Clase II - Positivo moderado (0.71-3.50)'},
  // Cualitativos
  {id:146,type:'qualitative',exam:'VDRL',qualResult:'No Reactivo',date:'2026-03-14',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:147,type:'qualitative',exam:'Hepatitis A IgM',qualResult:'No Reactivo',date:'2026-03-14',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:148,type:'qualitative',exam:'Hepatitis A IgG',qualResult:'No Reactivo',date:'2026-03-14',cat:'Serologia',lab:'BioNet La Florida',notes:'Lectura 0.17'},
  {id:149,type:'qualitative',exam:'Herpes II IgG',qualResult:'No Reactivo',date:'2026-03-14',cat:'Serologia',lab:'BioNet La Florida',notes:'Valor 0.14'},
  {id:150,type:'qualitative',exam:'Herpes I IgM',qualResult:'No Reactivo',date:'2026-03-14',cat:'Serologia',lab:'BioNet La Florida',notes:'Valor 0.52'},
  {id:151,type:'qualitative',exam:'Orina - Leucocitos',qualResult:'Negativo',date:'2026-03-14',cat:'Orina',lab:'BioNet La Florida',notes:''},
  {id:152,type:'qualitative',exam:'Orina - Nitritos',qualResult:'Negativo',date:'2026-03-14',cat:'Orina',lab:'BioNet La Florida',notes:''},
  {id:153,type:'qualitative',exam:'Orina - Proteinas',qualResult:'Negativo',date:'2026-03-14',cat:'Orina',lab:'BioNet La Florida',notes:''},
  {id:154,type:'qualitative',exam:'Orina - Glucosa',qualResult:'Negativo',date:'2026-03-14',cat:'Orina',lab:'BioNet La Florida',notes:''},

  // === 23/11/2020 - BioNet La Florida (24 años) ===
  // Perfil Bioquimico
  {id:155,type:'numeric',exam:'Glucosa',value:85,unit:'mg/dL',date:'2020-11-23',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:156,type:'numeric',exam:'Nitrogeno ureico',value:10,unit:'mg/dL',date:'2020-11-23',cat:'Rinon',lab:'BioNet La Florida',notes:''},
  {id:157,type:'numeric',exam:'Uremia',value:21,unit:'mg/dL',date:'2020-11-23',cat:'Rinon',lab:'BioNet La Florida',notes:''},
  {id:158,type:'numeric',exam:'Colesterol total',value:205,unit:'mg/dL',date:'2020-11-23',cat:'Sangre',lab:'BioNet La Florida',notes:'Elevado'},
  {id:159,type:'numeric',exam:'Acido urico',value:3.5,unit:'mg/dL',date:'2020-11-23',cat:'Rinon',lab:'BioNet La Florida',notes:''},
  {id:160,type:'numeric',exam:'Proteinas totales',value:7.4,unit:'gr/dL',date:'2020-11-23',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:161,type:'numeric',exam:'Albumina',value:4.4,unit:'gr/dL',date:'2020-11-23',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:162,type:'numeric',exam:'Calcio',value:9.6,unit:'mg/dL',date:'2020-11-23',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:163,type:'numeric',exam:'Fosforo',value:3.5,unit:'mg/dL',date:'2020-11-23',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:164,type:'numeric',exam:'Bilirrubina total',value:0.9,unit:'mg/dL',date:'2020-11-23',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:165,type:'numeric',exam:'Fosfatasa alcalina',value:62,unit:'U/L',date:'2020-11-23',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:166,type:'numeric',exam:'LDH',value:173,unit:'U/L',date:'2020-11-23',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:167,type:'numeric',exam:'SGOT-GOT',value:34,unit:'U/L',date:'2020-11-23',cat:'Higado',lab:'BioNet La Florida',notes:''},
  // Perfil Lipidico
  {id:168,type:'numeric',exam:'Colesterol HDL',value:52.1,unit:'mg/dL',date:'2020-11-23',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:169,type:'numeric',exam:'Colesterol LDL',value:133.9,unit:'mg/dL',date:'2020-11-23',cat:'Sangre',lab:'BioNet La Florida',notes:'Limite alto'},
  {id:170,type:'numeric',exam:'Colesterol VLDL',value:19,unit:'mg/dL',date:'2020-11-23',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:171,type:'numeric',exam:'Trigliceridos',value:95,unit:'mg/dL',date:'2020-11-23',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  // Perfil Hepatico
  {id:172,type:'numeric',exam:'Bilirrubina directa',value:0.20,unit:'mg/dL',date:'2020-11-23',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:173,type:'numeric',exam:'SGPT-GPT',value:77,unit:'U/L',date:'2020-11-23',cat:'Higado',lab:'BioNet La Florida',notes:'Elevado - fuera de rango (16-63)'},
  {id:174,type:'numeric',exam:'GGT',value:23,unit:'U/L',date:'2020-11-23',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:175,type:'numeric',exam:'Protrombina',value:93.3,unit:'%',date:'2020-11-23',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:176,type:'numeric',exam:'INR',value:1.04,unit:'ratio',date:'2020-11-23',cat:'Higado',lab:'BioNet La Florida',notes:''},
  // Tiroides
  {id:177,type:'numeric',exam:'TSH',value:1.56,unit:'mUI/L',date:'2020-11-23',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:178,type:'numeric',exam:'T4 libre',value:1.34,unit:'ng/dL',date:'2020-11-23',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:179,type:'numeric',exam:'T4 total',value:7.8,unit:'ug/dL',date:'2020-11-23',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:180,type:'numeric',exam:'T3 total',value:1.13,unit:'ng/mL',date:'2020-11-23',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  // Hemograma
  {id:181,type:'numeric',exam:'Hemoglobina',value:16.7,unit:'gr/dL',date:'2020-11-23',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:182,type:'numeric',exam:'Hematocrito',value:50.0,unit:'%',date:'2020-11-23',cat:'Sangre',lab:'BioNet La Florida',notes:'Limite alto'},
  {id:183,type:'numeric',exam:'VCM',value:101.4,unit:'fL',date:'2020-11-23',cat:'Sangre',lab:'BioNet La Florida',notes:'Macrocitosis leve - fuera de rango (82-99)'},
  {id:184,type:'numeric',exam:'HCM',value:33.8,unit:'pg',date:'2020-11-23',cat:'Sangre',lab:'BioNet La Florida',notes:'Fuera de rango (28-32)'},
  {id:185,type:'numeric',exam:'CHCM',value:33.4,unit:'gr/dL',date:'2020-11-23',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:186,type:'numeric',exam:'RDW',value:12.1,unit:'%',date:'2020-11-23',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:187,type:'numeric',exam:'Plaquetas',value:237,unit:'k/uL',date:'2020-11-23',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:188,type:'numeric',exam:'Leucocitos',value:4.4,unit:'k/uL',date:'2020-11-23',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  // Cualitativos
  {id:189,type:'qualitative',exam:'VIH Anticuerpos',qualResult:'No Reactivo',date:'2020-11-23',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:190,type:'qualitative',exam:'VDRL',qualResult:'No Reactivo',date:'2020-11-23',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:191,type:'qualitative',exam:'Orina - Leucocitos',qualResult:'Negativo',date:'2020-11-23',cat:'Orina',lab:'BioNet La Florida',notes:''},
  {id:192,type:'qualitative',exam:'Orina - Nitritos',qualResult:'Negativo',date:'2020-11-23',cat:'Orina',lab:'BioNet La Florida',notes:''},
  {id:193,type:'qualitative',exam:'Orina - Proteinas',qualResult:'Negativo',date:'2020-11-23',cat:'Orina',lab:'BioNet La Florida',notes:''},
  {id:194,type:'qualitative',exam:'Orina - Glucosa',qualResult:'Negativo',date:'2020-11-23',cat:'Orina',lab:'BioNet La Florida',notes:''},

  // === 01/10/2021 - BioNet La Florida (25 años) ===
  {id:195,type:'numeric',exam:'Creatinina',value:0.9,unit:'mg/dL',date:'2021-10-01',cat:'Rinon',lab:'BioNet La Florida',notes:''},
  {id:196,type:'numeric',exam:'Vitamina B12',value:320,unit:'pg/mL',date:'2021-10-01',cat:'Vitaminas',lab:'BioNet La Florida',notes:''},
  {id:197,type:'numeric',exam:'Vitamina D',value:14.48,unit:'ng/mL',date:'2021-10-01',cat:'Vitaminas',lab:'BioNet La Florida',notes:'Deficiencia - bajo rango (20-100)'},
  {id:198,type:'numeric',exam:'HbA1c',value:4.9,unit:'%',date:'2021-10-01',cat:'Sangre',lab:'BioNet La Florida',notes:'Ref menor o igual a 6'},
  {id:199,type:'numeric',exam:'Glucosa',value:79,unit:'mg/dL',date:'2021-10-01',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:200,type:'numeric',exam:'Nitrogeno ureico',value:15,unit:'mg/dL',date:'2021-10-01',cat:'Rinon',lab:'BioNet La Florida',notes:''},
  {id:201,type:'numeric',exam:'Uremia',value:32,unit:'mg/dL',date:'2021-10-01',cat:'Rinon',lab:'BioNet La Florida',notes:''},
  {id:202,type:'numeric',exam:'Colesterol total',value:181,unit:'mg/dL',date:'2021-10-01',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:203,type:'numeric',exam:'Acido urico',value:3.4,unit:'mg/dL',date:'2021-10-01',cat:'Rinon',lab:'BioNet La Florida',notes:'Bajo rango (3.5-7.2)'},
  {id:204,type:'numeric',exam:'Proteinas totales',value:7.2,unit:'gr/dL',date:'2021-10-01',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:205,type:'numeric',exam:'Albumina',value:4.1,unit:'gr/dL',date:'2021-10-01',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:206,type:'numeric',exam:'Calcio',value:9.7,unit:'mg/dL',date:'2021-10-01',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:207,type:'numeric',exam:'Fosforo',value:3.0,unit:'mg/dL',date:'2021-10-01',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:208,type:'numeric',exam:'Bilirrubina total',value:0.9,unit:'mg/dL',date:'2021-10-01',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:209,type:'numeric',exam:'Fosfatasa alcalina',value:61,unit:'U/L',date:'2021-10-01',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:210,type:'numeric',exam:'LDH',value:171,unit:'U/L',date:'2021-10-01',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:211,type:'numeric',exam:'SGOT-GOT',value:16,unit:'U/L',date:'2021-10-01',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:212,type:'numeric',exam:'Colesterol HDL',value:46.9,unit:'mg/dL',date:'2021-10-01',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:213,type:'numeric',exam:'Colesterol LDL',value:119.9,unit:'mg/dL',date:'2021-10-01',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:214,type:'numeric',exam:'Colesterol VLDL',value:14.2,unit:'mg/dL',date:'2021-10-01',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:215,type:'numeric',exam:'Trigliceridos',value:71,unit:'mg/dL',date:'2021-10-01',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:216,type:'numeric',exam:'Bilirrubina directa',value:0.30,unit:'mg/dL',date:'2021-10-01',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:217,type:'numeric',exam:'SGPT-GPT',value:20,unit:'U/L',date:'2021-10-01',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:218,type:'numeric',exam:'GGT',value:14,unit:'U/L',date:'2021-10-01',cat:'Higado',lab:'BioNet La Florida',notes:'Bajo rango (15-85)'},
  {id:219,type:'numeric',exam:'Protrombina',value:87.9,unit:'%',date:'2021-10-01',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:220,type:'numeric',exam:'INR',value:1.06,unit:'ratio',date:'2021-10-01',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:221,type:'numeric',exam:'TSH',value:1.61,unit:'mUI/L',date:'2021-10-01',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:222,type:'numeric',exam:'T4 libre',value:1.34,unit:'ng/dL',date:'2021-10-01',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:223,type:'numeric',exam:'T4 total',value:7,unit:'ug/dL',date:'2021-10-01',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:224,type:'numeric',exam:'T3 total',value:1.16,unit:'ng/mL',date:'2021-10-01',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:225,type:'numeric',exam:'Insulina basal',value:9.1,unit:'uUI/mL',date:'2021-10-01',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:226,type:'numeric',exam:'HOMA IR',value:1.7,unit:'indice',date:'2021-10-01',cat:'Sangre',lab:'BioNet La Florida',notes:'Ref menos de 2.5'},
  {id:227,type:'numeric',exam:'Hemoglobina',value:15.9,unit:'gr/dL',date:'2021-10-01',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:228,type:'numeric',exam:'Hematocrito',value:46.0,unit:'%',date:'2021-10-01',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:229,type:'numeric',exam:'VCM',value:98.4,unit:'fL',date:'2021-10-01',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:230,type:'numeric',exam:'HCM',value:34,unit:'pg',date:'2021-10-01',cat:'Sangre',lab:'BioNet La Florida',notes:'Fuera de rango (28-32)'},
  {id:231,type:'numeric',exam:'CHCM',value:34.6,unit:'gr/dL',date:'2021-10-01',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:232,type:'numeric',exam:'RDW',value:11.9,unit:'%',date:'2021-10-01',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:233,type:'numeric',exam:'Plaquetas',value:238,unit:'k/uL',date:'2021-10-01',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:234,type:'numeric',exam:'Leucocitos',value:5.2,unit:'k/uL',date:'2021-10-01',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:235,type:'qualitative',exam:'VDRL',qualResult:'No Reactivo',date:'2021-10-01',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:236,type:'qualitative',exam:'VIH Anticuerpos',qualResult:'No Reactivo',date:'2021-10-01',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:237,type:'qualitative',exam:'Hepatitis B HBsAg',qualResult:'No Reactivo',date:'2021-10-01',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:238,type:'qualitative',exam:'Hepatitis C Anti-HVC',qualResult:'No Reactivo',date:'2021-10-01',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:239,type:'qualitative',exam:'Urocultivo',qualResult:'Negativo',date:'2021-10-01',cat:'Orina',lab:'BioNet La Florida',notes:'0 UFC/mL - 24h incubacion'},
  {id:240,type:'qualitative',exam:'Orina - Leucocitos',qualResult:'Negativo',date:'2021-10-01',cat:'Orina',lab:'BioNet La Florida',notes:''},
  {id:241,type:'qualitative',exam:'Orina - Nitritos',qualResult:'Negativo',date:'2021-10-01',cat:'Orina',lab:'BioNet La Florida',notes:''},
  {id:242,type:'qualitative',exam:'Orina - Proteinas',qualResult:'Negativo',date:'2021-10-01',cat:'Orina',lab:'BioNet La Florida',notes:''},
  {id:243,type:'qualitative',exam:'Orina - Glucosa',qualResult:'Negativo',date:'2021-10-01',cat:'Orina',lab:'BioNet La Florida',notes:''},

  // === 26/03/2022 - BioNet La Florida (25 años) ===
  {id:244,type:'numeric',exam:'Creatinina',value:0.92,unit:'mg/dL',date:'2022-03-26',cat:'Rinon',lab:'BioNet La Florida',notes:''},
  {id:245,type:'numeric',exam:'Vitamina B12',value:323,unit:'pg/mL',date:'2022-03-26',cat:'Vitaminas',lab:'BioNet La Florida',notes:''},
  {id:246,type:'numeric',exam:'HbA1c',value:4.9,unit:'%',date:'2022-03-26',cat:'Sangre',lab:'BioNet La Florida',notes:'Ref menor o igual a 6'},
  {id:247,type:'numeric',exam:'Glucosa',value:88,unit:'mg/dL',date:'2022-03-26',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:248,type:'numeric',exam:'Nitrogeno ureico',value:12,unit:'mg/dL',date:'2022-03-26',cat:'Rinon',lab:'BioNet La Florida',notes:''},
  {id:249,type:'numeric',exam:'Uremia',value:26,unit:'mg/dL',date:'2022-03-26',cat:'Rinon',lab:'BioNet La Florida',notes:''},
  {id:250,type:'numeric',exam:'Colesterol total',value:185,unit:'mg/dL',date:'2022-03-26',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:251,type:'numeric',exam:'Acido urico',value:3.5,unit:'mg/dL',date:'2022-03-26',cat:'Rinon',lab:'BioNet La Florida',notes:''},
  {id:252,type:'numeric',exam:'Proteinas totales',value:6.9,unit:'gr/dL',date:'2022-03-26',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:253,type:'numeric',exam:'Albumina',value:4.1,unit:'gr/dL',date:'2022-03-26',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:254,type:'numeric',exam:'Calcio',value:9.8,unit:'mg/dL',date:'2022-03-26',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:255,type:'numeric',exam:'Fosforo',value:3.3,unit:'mg/dL',date:'2022-03-26',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:256,type:'numeric',exam:'Bilirrubina total',value:0.8,unit:'mg/dL',date:'2022-03-26',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:257,type:'numeric',exam:'Fosfatasa alcalina',value:57,unit:'U/L',date:'2022-03-26',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:258,type:'numeric',exam:'LDH',value:134,unit:'U/L',date:'2022-03-26',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:259,type:'numeric',exam:'SGOT-GOT',value:21,unit:'U/L',date:'2022-03-26',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:260,type:'numeric',exam:'Colesterol HDL',value:41.4,unit:'mg/dL',date:'2022-03-26',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:261,type:'numeric',exam:'Colesterol LDL',value:111.2,unit:'mg/dL',date:'2022-03-26',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:262,type:'numeric',exam:'Colesterol VLDL',value:32.4,unit:'mg/dL',date:'2022-03-26',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:263,type:'numeric',exam:'Trigliceridos',value:162,unit:'mg/dL',date:'2022-03-26',cat:'Sangre',lab:'BioNet La Florida',notes:'Limite alto (150-199)'},
  {id:264,type:'numeric',exam:'TSH',value:1.41,unit:'mUI/L',date:'2022-03-26',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:265,type:'numeric',exam:'T4 libre',value:1.28,unit:'ng/dL',date:'2022-03-26',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:266,type:'numeric',exam:'Insulina basal',value:5.7,unit:'uUI/mL',date:'2022-03-26',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:267,type:'numeric',exam:'HOMA IR',value:1.2,unit:'indice',date:'2022-03-26',cat:'Sangre',lab:'BioNet La Florida',notes:'Ref menos de 2.5'},
  {id:268,type:'numeric',exam:'Hemoglobina',value:16.1,unit:'gr/dL',date:'2022-03-26',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:269,type:'numeric',exam:'Hematocrito',value:48.2,unit:'%',date:'2022-03-26',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:270,type:'numeric',exam:'VCM',value:100.6,unit:'fL',date:'2022-03-26',cat:'Sangre',lab:'BioNet La Florida',notes:'Macrocitosis leve - fuera de rango (82-99)'},
  {id:271,type:'numeric',exam:'HCM',value:33.6,unit:'pg',date:'2022-03-26',cat:'Sangre',lab:'BioNet La Florida',notes:'Fuera de rango (28-32)'},
  {id:272,type:'numeric',exam:'CHCM',value:33.4,unit:'gr/dL',date:'2022-03-26',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:273,type:'numeric',exam:'RDW',value:12.2,unit:'%',date:'2022-03-26',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:274,type:'numeric',exam:'Plaquetas',value:238,unit:'k/uL',date:'2022-03-26',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:275,type:'numeric',exam:'Leucocitos',value:4.8,unit:'k/uL',date:'2022-03-26',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:276,type:'qualitative',exam:'VDRL',qualResult:'No Reactivo',date:'2022-03-26',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:277,type:'qualitative',exam:'VIH Anticuerpos',qualResult:'No Reactivo',date:'2022-03-26',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:278,type:'qualitative',exam:'Urocultivo',qualResult:'Negativo',date:'2022-03-26',cat:'Orina',lab:'BioNet La Florida',notes:'0 UFC/mL - 24h incubacion'},
  {id:279,type:'qualitative',exam:'Orina - Leucocitos',qualResult:'Negativo',date:'2022-03-26',cat:'Orina',lab:'BioNet La Florida',notes:''},
  {id:280,type:'qualitative',exam:'Orina - Nitritos',qualResult:'Negativo',date:'2022-03-26',cat:'Orina',lab:'BioNet La Florida',notes:''},
  {id:281,type:'qualitative',exam:'Orina - Proteinas',qualResult:'Negativo',date:'2022-03-26',cat:'Orina',lab:'BioNet La Florida',notes:''},
  {id:282,type:'qualitative',exam:'Orina - Glucosa',qualResult:'Negativo',date:'2022-03-26',cat:'Orina',lab:'BioNet La Florida',notes:''},

  // === 10/01/2023 - BioNet La Florida (26 años) ===
  {id:283,type:'numeric',exam:'Creatinina',value:0.92,unit:'mg/dL',date:'2023-01-10',cat:'Rinon',lab:'BioNet La Florida',notes:''},
  {id:284,type:'numeric',exam:'Vitamina B12',value:220,unit:'pg/mL',date:'2023-01-10',cat:'Vitaminas',lab:'BioNet La Florida',notes:''},
  {id:285,type:'numeric',exam:'Vitamina D',value:42.64,unit:'ng/mL',date:'2023-01-10',cat:'Vitaminas',lab:'BioNet La Florida',notes:''},
  {id:286,type:'numeric',exam:'HbA1c',value:4.8,unit:'%',date:'2023-01-10',cat:'Sangre',lab:'BioNet La Florida',notes:'Ref menor o igual a 6'},
  {id:287,type:'numeric',exam:'Glucosa',value:85,unit:'mg/dL',date:'2023-01-10',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:288,type:'numeric',exam:'Nitrogeno ureico',value:11,unit:'mg/dL',date:'2023-01-10',cat:'Rinon',lab:'BioNet La Florida',notes:''},
  {id:289,type:'numeric',exam:'Uremia',value:24,unit:'mg/dL',date:'2023-01-10',cat:'Rinon',lab:'BioNet La Florida',notes:''},
  {id:290,type:'numeric',exam:'Colesterol total',value:162,unit:'mg/dL',date:'2023-01-10',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:291,type:'numeric',exam:'Acido urico',value:4.1,unit:'mg/dL',date:'2023-01-10',cat:'Rinon',lab:'BioNet La Florida',notes:''},
  {id:292,type:'numeric',exam:'Proteinas totales',value:7.3,unit:'gr/dL',date:'2023-01-10',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:293,type:'numeric',exam:'Albumina',value:4.2,unit:'gr/dL',date:'2023-01-10',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:294,type:'numeric',exam:'Calcio',value:9.4,unit:'mg/dL',date:'2023-01-10',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:295,type:'numeric',exam:'Fosforo',value:3.3,unit:'mg/dL',date:'2023-01-10',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:296,type:'numeric',exam:'Bilirrubina total',value:0.9,unit:'mg/dL',date:'2023-01-10',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:297,type:'numeric',exam:'Fosfatasa alcalina',value:50,unit:'U/L',date:'2023-01-10',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:298,type:'numeric',exam:'LDH',value:174,unit:'U/L',date:'2023-01-10',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:299,type:'numeric',exam:'SGOT-GOT',value:68,unit:'U/L',date:'2023-01-10',cat:'Higado',lab:'BioNet La Florida',notes:'Elevado - fuera de rango (5-37)'},
  {id:300,type:'numeric',exam:'Colesterol HDL',value:45.7,unit:'mg/dL',date:'2023-01-10',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:301,type:'numeric',exam:'Colesterol LDL',value:102.9,unit:'mg/dL',date:'2023-01-10',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:302,type:'numeric',exam:'Colesterol VLDL',value:13.4,unit:'mg/dL',date:'2023-01-10',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:303,type:'numeric',exam:'Trigliceridos',value:67,unit:'mg/dL',date:'2023-01-10',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:304,type:'numeric',exam:'Bilirrubina directa',value:0.30,unit:'mg/dL',date:'2023-01-10',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:305,type:'numeric',exam:'SGPT-GPT',value:34,unit:'U/L',date:'2023-01-10',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:306,type:'numeric',exam:'GGT',value:14,unit:'U/L',date:'2023-01-10',cat:'Higado',lab:'BioNet La Florida',notes:'Bajo rango (15-85)'},
  {id:307,type:'numeric',exam:'Protrombina',value:84.5,unit:'%',date:'2023-01-10',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:308,type:'numeric',exam:'INR',value:1.09,unit:'ratio',date:'2023-01-10',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:309,type:'numeric',exam:'TSH',value:1.21,unit:'mUI/L',date:'2023-01-10',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:310,type:'numeric',exam:'T4 libre',value:1.34,unit:'ng/dL',date:'2023-01-10',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:311,type:'numeric',exam:'Insulina basal',value:5.7,unit:'uUI/mL',date:'2023-01-10',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:312,type:'numeric',exam:'Sodio',value:141,unit:'mEq/L',date:'2023-01-10',cat:'Electrolitos',lab:'BioNet La Florida',notes:''},
  {id:313,type:'numeric',exam:'Potasio',value:4.1,unit:'mEq/L',date:'2023-01-10',cat:'Electrolitos',lab:'BioNet La Florida',notes:''},
  {id:314,type:'numeric',exam:'Cloro',value:106,unit:'mEq/L',date:'2023-01-10',cat:'Electrolitos',lab:'BioNet La Florida',notes:''},
  {id:315,type:'numeric',exam:'Hemoglobina',value:15.9,unit:'gr/dL',date:'2023-01-10',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:316,type:'numeric',exam:'Hematocrito',value:47.8,unit:'%',date:'2023-01-10',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:317,type:'numeric',exam:'VCM',value:97.7,unit:'fL',date:'2023-01-10',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:318,type:'numeric',exam:'HCM',value:32.6,unit:'pg',date:'2023-01-10',cat:'Sangre',lab:'BioNet La Florida',notes:'Fuera de rango (28-32)'},
  {id:319,type:'numeric',exam:'CHCM',value:33.3,unit:'gr/dL',date:'2023-01-10',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:320,type:'numeric',exam:'RDW',value:12.2,unit:'%',date:'2023-01-10',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:321,type:'numeric',exam:'Plaquetas',value:214,unit:'k/uL',date:'2023-01-10',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:322,type:'numeric',exam:'Leucocitos',value:4.0,unit:'k/uL',date:'2023-01-10',cat:'Sangre',lab:'BioNet La Florida',notes:'Limite bajo (4.1-9.5)'},
  {id:323,type:'qualitative',exam:'VDRL',qualResult:'No Reactivo',date:'2023-01-10',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:324,type:'qualitative',exam:'Orina - Leucocitos',qualResult:'Negativo',date:'2023-01-10',cat:'Orina',lab:'BioNet La Florida',notes:''},
  {id:325,type:'qualitative',exam:'Orina - Nitritos',qualResult:'Negativo',date:'2023-01-10',cat:'Orina',lab:'BioNet La Florida',notes:''},
  {id:326,type:'qualitative',exam:'Orina - Proteinas',qualResult:'Negativo',date:'2023-01-10',cat:'Orina',lab:'BioNet La Florida',notes:''},
  {id:327,type:'qualitative',exam:'Orina - Glucosa',qualResult:'Negativo',date:'2023-01-10',cat:'Orina',lab:'BioNet La Florida',notes:''},

  // === 11/09/2024 - BioNet La Florida (28 años) ===
  {id:328,type:'numeric',exam:'Creatinina',value:0.97,unit:'mg/dL',date:'2024-09-11',cat:'Rinon',lab:'BioNet La Florida',notes:''},
  {id:329,type:'numeric',exam:'Vitamina B12',value:326,unit:'pg/mL',date:'2024-09-11',cat:'Vitaminas',lab:'BioNet La Florida',notes:''},
  {id:330,type:'numeric',exam:'Vitamina D',value:10.11,unit:'ng/mL',date:'2024-09-11',cat:'Vitaminas',lab:'BioNet La Florida',notes:'Deficiencia severa - bajo rango (20-100)'},
  {id:331,type:'numeric',exam:'Glucosa',value:85,unit:'mg/dL',date:'2024-09-11',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:332,type:'numeric',exam:'Nitrogeno ureico',value:14,unit:'mg/dL',date:'2024-09-11',cat:'Rinon',lab:'BioNet La Florida',notes:''},
  {id:333,type:'numeric',exam:'Uremia',value:30,unit:'mg/dL',date:'2024-09-11',cat:'Rinon',lab:'BioNet La Florida',notes:''},
  {id:334,type:'numeric',exam:'Colesterol total',value:177,unit:'mg/dL',date:'2024-09-11',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:335,type:'numeric',exam:'Acido urico',value:3.5,unit:'mg/dL',date:'2024-09-11',cat:'Rinon',lab:'BioNet La Florida',notes:''},
  {id:336,type:'numeric',exam:'Proteinas totales',value:7.4,unit:'gr/dL',date:'2024-09-11',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:337,type:'numeric',exam:'Albumina',value:4.2,unit:'gr/dL',date:'2024-09-11',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:338,type:'numeric',exam:'Calcio',value:9,unit:'mg/dL',date:'2024-09-11',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:339,type:'numeric',exam:'Fosforo',value:3.9,unit:'mg/dL',date:'2024-09-11',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:340,type:'numeric',exam:'Bilirrubina total',value:1.4,unit:'mg/dL',date:'2024-09-11',cat:'Higado',lab:'BioNet La Florida',notes:'Elevado - fuera de rango (0.3-1.2)'},
  {id:341,type:'numeric',exam:'Fosfatasa alcalina',value:54,unit:'U/L',date:'2024-09-11',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:342,type:'numeric',exam:'LDH',value:148,unit:'U/L',date:'2024-09-11',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:343,type:'numeric',exam:'SGOT-GOT',value:9,unit:'U/L',date:'2024-09-11',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:344,type:'numeric',exam:'Bilirrubina directa',value:0.50,unit:'mg/dL',date:'2024-09-11',cat:'Higado',lab:'BioNet La Florida',notes:'Elevado - fuera de rango (0-0.30)'},
  {id:345,type:'numeric',exam:'Bilirrubina indirecta',value:0.90,unit:'mg/dL',date:'2024-09-11',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:346,type:'numeric',exam:'SGPT-GPT',value:17,unit:'U/L',date:'2024-09-11',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:347,type:'numeric',exam:'GGT',value:18,unit:'U/L',date:'2024-09-11',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:348,type:'numeric',exam:'Protrombina',value:105.1,unit:'%',date:'2024-09-11',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:349,type:'numeric',exam:'INR',value:0.97,unit:'ratio',date:'2024-09-11',cat:'Higado',lab:'BioNet La Florida',notes:''},
  {id:350,type:'numeric',exam:'TSH',value:1.53,unit:'mUI/L',date:'2024-09-11',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:351,type:'numeric',exam:'T4 libre',value:1.66,unit:'ng/dL',date:'2024-09-11',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:352,type:'numeric',exam:'T4 total',value:8.6,unit:'ug/dL',date:'2024-09-11',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:353,type:'numeric',exam:'T3 total',value:1.29,unit:'ng/mL',date:'2024-09-11',cat:'Tiroides',lab:'BioNet La Florida',notes:''},
  {id:354,type:'numeric',exam:'Insulina basal',value:9.7,unit:'uUI/mL',date:'2024-09-11',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:355,type:'numeric',exam:'HOMA IR',value:2,unit:'indice',date:'2024-09-11',cat:'Sangre',lab:'BioNet La Florida',notes:'Ref menos de 2.5'},
  {id:356,type:'numeric',exam:'Sodio',value:140,unit:'mEq/L',date:'2024-09-11',cat:'Electrolitos',lab:'BioNet La Florida',notes:''},
  {id:357,type:'numeric',exam:'Potasio',value:4.4,unit:'mEq/L',date:'2024-09-11',cat:'Electrolitos',lab:'BioNet La Florida',notes:''},
  {id:358,type:'numeric',exam:'Cloro',value:104,unit:'mEq/L',date:'2024-09-11',cat:'Electrolitos',lab:'BioNet La Florida',notes:''},
  {id:359,type:'numeric',exam:'Hemoglobina',value:15.5,unit:'gr/dL',date:'2024-09-11',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:360,type:'numeric',exam:'Hematocrito',value:45.2,unit:'%',date:'2024-09-11',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:361,type:'numeric',exam:'VCM',value:100.2,unit:'fL',date:'2024-09-11',cat:'Sangre',lab:'BioNet La Florida',notes:'Macrocitosis leve - fuera de rango (82-99)'},
  {id:362,type:'numeric',exam:'HCM',value:34.5,unit:'pg',date:'2024-09-11',cat:'Sangre',lab:'BioNet La Florida',notes:'Fuera de rango (28-32)'},
  {id:363,type:'numeric',exam:'CHCM',value:34.4,unit:'gr/dL',date:'2024-09-11',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:364,type:'numeric',exam:'RDW',value:11.8,unit:'%',date:'2024-09-11',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:365,type:'numeric',exam:'Plaquetas',value:213,unit:'k/uL',date:'2024-09-11',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:366,type:'numeric',exam:'Leucocitos',value:4.6,unit:'k/uL',date:'2024-09-11',cat:'Sangre',lab:'BioNet La Florida',notes:''},
  {id:367,type:'numeric',exam:'Herpes I IgG',value:3.6,unit:'Index Value',date:'2024-09-11',cat:'Serologia',lab:'BioNet La Florida',notes:'Positivo (>1.1) - seropositivo HSV-1'},
  {id:368,type:'numeric',exam:'Herpes II IgG',value:0.2,unit:'Index Value',date:'2024-09-11',cat:'Serologia',lab:'BioNet La Florida',notes:'Negativo (<0.90)'},
  {id:369,type:'qualitative',exam:'VDRL',qualResult:'No Reactivo',date:'2024-09-11',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:370,type:'qualitative',exam:'VIH Anticuerpos',qualResult:'No Reactivo',date:'2024-09-11',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:371,type:'qualitative',exam:'Hepatitis B HBsAg',qualResult:'No Reactivo',date:'2024-09-11',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:372,type:'qualitative',exam:'Hepatitis C Anti-HVC',qualResult:'No Reactivo',date:'2024-09-11',cat:'Serologia',lab:'BioNet La Florida',notes:''},
  {id:373,type:'qualitative',exam:'Panel ITS PCR',qualResult:'Negativo',date:'2024-09-11',cat:'Serologia',lab:'BioNet La Florida',notes:'5 patogenos negativos: Chlamydia, Gonorrhoeae, Mycoplasma hominis, Mycoplasma genitalium, Ureaplasma spp'},
  {id:374,type:'qualitative',exam:'Orina - Leucocitos',qualResult:'Negativo',date:'2024-09-11',cat:'Orina',lab:'BioNet La Florida',notes:''},
  {id:375,type:'qualitative',exam:'Orina - Nitritos',qualResult:'Negativo',date:'2024-09-11',cat:'Orina',lab:'BioNet La Florida',notes:''},
  {id:376,type:'qualitative',exam:'Orina - Proteinas',qualResult:'Negativo',date:'2024-09-11',cat:'Orina',lab:'BioNet La Florida',notes:''},
  {id:377,type:'qualitative',exam:'Orina - Glucosa',qualResult:'Negativo',date:'2024-09-11',cat:'Orina',lab:'BioNet La Florida',notes:''}
];
var APP_SK = "miSalud_v7";
var REFS = {
  'Glucosa':{min:70,max:100,unit:'mg/dL',cat:'Sangre'},
  'Colesterol total':{min:0,max:200,unit:'mg/dL',cat:'Sangre'},
  'Colesterol HDL':{min:40,max:60,unit:'mg/dL',cat:'Sangre'},
  'Colesterol LDL':{min:0,max:130,unit:'mg/dL',cat:'Sangre'},
  'Trigliceridos':{min:0,max:150,unit:'mg/dL',cat:'Sangre'},
  'Hemoglobina':{min:13,max:17,unit:'gr/dL',cat:'Sangre'},
  'Hematocrito':{min:41,max:49,unit:'%',cat:'Sangre'},
  'Leucocitos':{min:4.1,max:9.5,unit:'k/uL',cat:'Sangre'},
  'Plaquetas':{min:150,max:350,unit:'k/uL',cat:'Sangre'},
  'Calcio':{min:8.3,max:10.6,unit:'mg/dL',cat:'Sangre'},
  'Fosforo':{min:2.4,max:5.1,unit:'mg/dL',cat:'Sangre'},
  'Insulina basal':{min:3,max:25,unit:'uUI/mL',cat:'Sangre'},
  'Creatinina':{min:0.7,max:1.3,unit:'mg/dL',cat:'Rinon'},
  'Acido urico':{min:3.5,max:7.2,unit:'mg/dL',cat:'Rinon'},
  'Proteinas totales':{min:5.7,max:8.2,unit:'gr/dL',cat:'Higado'},
  'Albumina':{min:3.4,max:5,unit:'gr/dL',cat:'Higado'},
  'Bilirrubina total':{min:0.3,max:1.2,unit:'mg/dL',cat:'Higado'},
  'Fosfatasa alcalina':{min:46,max:116,unit:'U/L',cat:'Higado'},
  'LDH':{min:85,max:227,unit:'U/L',cat:'Higado'},
  'SGOT-GOT':{min:5,max:37,unit:'U/L',cat:'Higado'},
  'SGPT-GPT':{min:16,max:63,unit:'U/L',cat:'Higado'},
  'GGT':{min:15,max:85,unit:'U/L',cat:'Higado'},
  'TSH':{min:0.55,max:4.78,unit:'mUI/L',cat:'Tiroides'},
  'T4 libre':{min:0.89,max:1.76,unit:'ng/dL',cat:'Tiroides'},
  'T4 total':{min:4.5,max:10.9,unit:'ug/dL',cat:'Tiroides'},
  'T3 total':{min:0.6,max:1.81,unit:'ng/mL',cat:'Tiroides'},
  'Vitamina D':{min:20,max:100,unit:'ng/mL',cat:'Vitaminas'},
  'Vitamina B12':{min:211,max:911,unit:'pg/mL',cat:'Vitaminas'},
  'Sodio':{min:136,max:145,unit:'mEq/L',cat:'Electrolitos'},
  'Potasio':{min:3.5,max:5.1,unit:'mEq/L',cat:'Electrolitos'},
  'Cloro':{min:98,max:107,unit:'mEq/L',cat:'Electrolitos'},
  'HOMA IR':{min:0,max:2.5,unit:'indice',cat:'Sangre'},
  'VCM':{min:82,max:99,unit:'fL',cat:'Sangre'},
  'HCM':{min:28,max:32,unit:'pg',cat:'Sangre'},
  'CHCM':{min:32,max:36,unit:'gr/dL',cat:'Sangre'},
  'RDW':{min:11.5,max:14.5,unit:'%',cat:'Sangre'},
  'IgE Dermatoph. pteronyssinus':{min:0,max:0.35,unit:'IU/mL',cat:'Alergias'},
  'IgE Dermatofagoide farinae':{min:0,max:0.35,unit:'IU/mL',cat:'Alergias'},
  'Nitrogeno ureico':{min:7,max:23,unit:'mg/dL',cat:'Rinon'},
  'Uremia':{min:15,max:49,unit:'mg/dL',cat:'Rinon'},
  'Bilirrubina directa':{min:0,max:0.30,unit:'mg/dL',cat:'Higado'},
  'Bilirrubina indirecta':{min:0.1,max:0.9,unit:'mg/dL',cat:'Higado'},
  'Colesterol VLDL':{min:0,max:30,unit:'mg/dL',cat:'Sangre'},
  'HbA1c':{min:0,max:6,unit:'%',cat:'Sangre'},
  'Protrombina':{min:70,max:130,unit:'%',cat:'Higado'},
  'INR':{min:0.8,max:1.2,unit:'ratio',cat:'Higado'},
  'Herpes I IgG':{min:0,max:0.90,unit:'Index Value',cat:'Serologia'},
  'Herpes II IgG':{min:0,max:0.90,unit:'Index Value',cat:'Serologia'}
};
var CAT_SCH = {
  'Sangre':{icon:'&#129978;',days:365,label:'Hemograma y bioquimica'},
  'Higado':{icon:'&#128153;',days:365,label:'Perfil hepatico'},
  'Rinon':{icon:'&#129386;',days:365,label:'Funcion renal'},
  'Tiroides':{icon:'&#129419;',days:365,label:'Perfil tiroideo'},
  'Vitaminas':{icon:'&#9728;',days:180,label:'Vitaminas D y B12'},
  'Electrolitos':{icon:'&#9889;',days:365,label:'Electrolitos'},
  'Serologia':{icon:'&#129514;',days:365,label:'Serologia / ITS'},
  'Alergias':{icon:'&#127807;',days:730,label:'Panel de alergenos IgE'},
  'Orina':{icon:'&#129748;',days:365,label:'Orina completa'},
  'Oftalmologia':{icon:'&#128065;',days:730,label:'Control visual'},
  'Estudios':{icon:'&#128300;',days:730,label:'Estudios de imagen'}
};
